version: '3.8'

services:
  node-app:
    build: .
    container_name: node-app
    restart: always
    ports:
      - "3000:3000"
    networks:
      - web

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app
    networks:
      - web

networks:
  web:
    driver: bridge
